# Numpy 기초

## 1. Numpy 란?

In [1]:
# numpy 사용하기
import numpy as np

## 2. Array 정의 및 사용하기

In [2]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [3]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [4]:
# numpy를 이용하여 array 정의하기
# 1. 위에서 만든 python list를 이용
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [5]:
# array의 형태(크기)를 확인할 수 있다.
arr1.shape

(5,)

In [6]:
# 2. 바로 python list를 넣어 줌으로써 만들기
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [7]:
arr2.shape

(5,)

In [8]:
# array의 자료형을 확인할 수 있다.
arr2.dtype

dtype('int32')

In [9]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [10]:
arr3.shape

(5,)

In [11]:
arr3.dtype

dtype('float64')

In [12]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr4.shape

(4, 3)

#### numpy shape
numpy에서는 해당 array의 크기를 알 수 있다.
shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.
위에서 arr1.shape의 결과는 (5,) 으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.
arr4.shape의 결과는 (4,3) 으로써, 2차원의 데이터이며 4 * 3 크기를 갖고 있는 array 이다.

#### numpy 자료형
arr1이나 arr2는 int64라는 자료형을 갖는 것에 반해 arr3는 float64라는 자료형을 갖는다.
이는 arr3내부 데이터를 살펴보면 3.5라는 실수형 데이터를 갖기 때문임을 알 수 있다.
numpy에서 사용되는 자료형은 아래와 같다. (자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오프젝트 object
- 유니코드 unicode_

### 2-1. np.zeros(), np.ones(), np.arange() 함수
numpy에서 array를 정의할 때 사용되는 함수들이다.

아래 실습을 통해 각각이 어떻게 다른지 살펴본다.

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# np.zeros() 함수는 인자로 받는 크기만큼, 모든요소가 0인 array를 만든다.
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
# np.ones() 함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만든다.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.

## 3. Array 연산
기본적으로 numpy에서 연산을 할때는 크기가 서로 동일한 array 끼리 연산이 진행된다.

이때 같은 위치에 있는 요소들 끼리 연산이 진행된다.

In [21]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr1.shape

(2, 3)

In [23]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [24]:
arr2.shape

(2, 3)

### 3-1. array 덧셈

In [25]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

### 3-2. array 뺄셈

In [26]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

### 3-3. array 곱셈

주의하자.

행렬의 곱처럼 곱셈이 진행되는 것이 아니라 각 요소별로 곱셈이 진행된다.

In [27]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

### 3-4. array 나눗셈

In [28]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

### 3-5. array의 브로드 캐스트
위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,

numpy에서는 브로드캐스트라는 기능을 제공한다.

브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것이다.

In [29]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr1.shape

(2, 3)

In [31]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [32]:
arr3.shape

(3,)

In [33]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [34]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

위와 같이 서로 크기가 다른 arr1과 arr3의 연산이 가능하다.

연산결과를 살펴보면 arr3이 [10,11,12] 에서 [[10,11,12],[10,11,12]]로 확장되어 계산되었음을 확인할 수 있다.

동일한 방식으로 하나의 array에 스칼라 연산도 가능하다.

In [35]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [36]:
# 요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

## 4. Array 인덱싱
numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.

이때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작하는 것에 주의한다.

In [37]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# 0번째 요소
arr1[0]

0

In [39]:
# 3번째 요소
arr1[3]

3

In [40]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [41]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

물론 1차원이 아닌 그 이상의 차원에서도 인덱싱이 가능하다.

In [42]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [43]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[0,0]

1

In [45]:
# 2행의 모든 요소 꺼내기
arr2[2,:]

array([ 9, 10, 11, 12])

In [46]:
# 2행의 3번째 요소 꺼내기
arr2[2,3]

12

In [47]:
# 모든 열의 3번째 요소 꺼내기
arr2[:,3]

array([ 4,  8, 12])

## 5. Array boolean 인덱싱(마스크)
위에서 이용한 다차원의 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.

해당 기능은 주로 마스크라고 이야기하는데, boolean인덱싱을 통해 만들어낸 array를 통해

우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.

즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.

In [48]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])

In [49]:
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [50]:
names.shape

(8,)

In [51]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4)

In [52]:
data

array([[ 1.02986075e-01, -2.85965500e-01, -9.53332180e-02,
        -1.03783853e+00],
       [-1.47098616e+00,  2.48175375e-01, -4.11326508e-02,
         9.46553228e-01],
       [-5.79017239e-05,  1.46966396e-01,  3.20944470e-01,
         2.12788308e-01],
       [ 7.54661298e-02,  5.02598535e-01, -3.08618745e-01,
        -2.00857369e-01],
       [ 1.72571788e+00,  2.45660833e-01,  2.08465882e+00,
         5.94220195e-01],
       [-5.27647945e-01,  7.63680535e-01,  2.57335407e-02,
        -9.99180503e-01],
       [ 6.35804923e-01, -1.47001715e+00,  8.89398205e-01,
        -3.08894172e-01],
       [-5.90964230e-01, -4.63108377e-01,  4.80102922e-01,
         6.43857814e-01]])

In [53]:
data.shape

(8, 4)

위와 같은 names와 data라는 array가 있다.

이때, names의 각 요소가 data의 각 행과 연결된다고 가정해보자.

그리고 이 때, names가 Beomwoo인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용한다.

In [54]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == 'Beomwoo')

In [55]:
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [56]:
data[names_Beomwoo_mask,:]

array([[ 0.10298607, -0.2859655 , -0.09533322, -1.03783853],
       [-1.47098616,  0.24817537, -0.04113265,  0.94655323],
       [-0.52764795,  0.76368054,  0.02573354, -0.9991805 ],
       [-0.59096423, -0.46310838,  0.48010292,  0.64385781]])

위의 결과를 보면, 요소가 Beomwoo인 것은 0번째, 1번째, 5번째, 7번째 이므로

data에서 0,1,5,7행의 모든 요소를 꺼내와야 한다.

이를 위해 요소가 Beomwoo인 것에 대한 boolean 값을 가지는 mask를 만들었고

마스크를 인덱싱에 응용하여 data의 0,1,5,7행을 꺼냈다.

In [57]:
# 요소가 Kim인 행의 데이터만 꺼내기
data[names == 'Kim',:]

array([[-5.79017239e-05,  1.46966396e-01,  3.20944470e-01,
         2.12788308e-01]])

In [58]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names == 'Kim') | (names == 'Park'),:]

array([[-5.79017239e-05,  1.46966396e-01,  3.20944470e-01,
         2.12788308e-01],
       [ 6.35804923e-01, -1.47001715e+00,  8.89398205e-01,
        -3.08894172e-01]])

물론 data array 자체적으로도 마스크를 만들고, 이를 응용하여 인덱싱이 가능하다.

data array에서 0번째 열의 값이 0보다 작은 행을 구해보자.

In [59]:
# 먼저 마스크를 만든다.
# data array에서 0번째 열이 0보다 작은 요소의 boolean 값은 다음과 같다.
data[:,0] < 0

array([False,  True,  True, False, False,  True, False,  True])

In [60]:
# 위에서 만든 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구한다.
data[data[:,0]<0,:]

array([[-1.47098616e+00,  2.48175375e-01, -4.11326508e-02,
         9.46553228e-01],
       [-5.79017239e-05,  1.46966396e-01,  3.20944470e-01,
         2.12788308e-01],
       [-5.27647945e-01,  7.63680535e-01,  2.57335407e-02,
        -9.99180503e-01],
       [-5.90964230e-01, -4.63108377e-01,  4.80102922e-01,
         6.43857814e-01]])

이를 통해 특정 위치에만 우리가 원하는 값을 대입할 수 있다.

위에서 얻은, 0번째 열의 값이 0보다 작은 행의 2,3번째 열값에 0을 대입해보자.

In [61]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열 값
data[data[:,0]<0,2:4]

array([[-0.04113265,  0.94655323],
       [ 0.32094447,  0.21278831],
       [ 0.02573354, -0.9991805 ],
       [ 0.48010292,  0.64385781]])

In [62]:
data[data[:,0]<0,2:4] = 0
data

array([[ 1.02986075e-01, -2.85965500e-01, -9.53332180e-02,
        -1.03783853e+00],
       [-1.47098616e+00,  2.48175375e-01,  0.00000000e+00,
         0.00000000e+00],
       [-5.79017239e-05,  1.46966396e-01,  0.00000000e+00,
         0.00000000e+00],
       [ 7.54661298e-02,  5.02598535e-01, -3.08618745e-01,
        -2.00857369e-01],
       [ 1.72571788e+00,  2.45660833e-01,  2.08465882e+00,
         5.94220195e-01],
       [-5.27647945e-01,  7.63680535e-01,  0.00000000e+00,
         0.00000000e+00],
       [ 6.35804923e-01, -1.47001715e+00,  8.89398205e-01,
        -3.08894172e-01],
       [-5.90964230e-01, -4.63108377e-01,  0.00000000e+00,
         0.00000000e+00]])

## 6. Numpy 함수
numpy에서는 array에 적용되는 다양한 함수가 있다.

### 6-1. 하나의 array에 적용되는 함수

In [63]:
arr1 = np.random.randn(5,3)
arr1

array([[-1.15496454,  0.59050021,  0.49390619],
       [-0.69146405,  0.40217602,  0.08806803],
       [-0.96063218, -0.33530954, -1.46980557],
       [-0.87641303,  0.05356809,  0.29419752],
       [-0.09170898, -0.46085955,  1.06521861]])

In [64]:
# 각 성분의 절대값 계산하기
np.abs(arr1)

array([[1.15496454, 0.59050021, 0.49390619],
       [0.69146405, 0.40217602, 0.08806803],
       [0.96063218, 0.33530954, 1.46980557],
       [0.87641303, 0.05356809, 0.29419752],
       [0.09170898, 0.46085955, 1.06521861]])

In [65]:
# 각 성분의 제곱근 계산하기 ( == array ** 0.5)
np.sqrt(arr1)

<ipython-input-65-1adcb47f53b6>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([[       nan, 0.76844011, 0.7027846 ],
       [       nan, 0.63417349, 0.29676258],
       [       nan,        nan,        nan],
       [       nan, 0.23144782, 0.54239977],
       [       nan,        nan, 1.03209428]])

In [66]:
# 각 성분의 제곱 계산하기
np.square(arr1)

array([[1.33394308, 0.34869049, 0.24394332],
       [0.47812253, 0.16174555, 0.00775598],
       [0.92281419, 0.11243249, 2.16032841],
       [0.7680998 , 0.00286954, 0.08655218],
       [0.00841054, 0.21239152, 1.13469068]])

In [67]:
# 각 성분을 무리수 e의 지수로 삼은 값을 계산하기
np.exp(arr1)

array([[0.31506871, 1.80489101, 1.63870482],
       [0.50084227, 1.49507447, 1.09206241],
       [0.3826509 , 0.7151167 , 0.22997019],
       [0.4162734 , 1.05502883, 1.34204895],
       [0.91237063, 0.63074126, 2.9014732 ]])

In [68]:
# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산하기
np.log(arr1)

<ipython-input-68-bddc4320f0c3>:2: RuntimeWarning: invalid value encountered in log
  np.log(arr1)


array([[        nan, -0.52678529, -0.70540968],
       [        nan, -0.91086542, -2.42964571],
       [        nan,         nan,         nan],
       [        nan, -2.92680167, -1.22350392],
       [        nan,         nan,  0.06318004]])

In [69]:
np.log10(arr1)

<ipython-input-69-53e7f8b3389a>:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr1)


array([[        nan, -0.22877995, -0.30635553],
       [        nan, -0.39558383, -1.05518173],
       [        nan,         nan,         nan],
       [        nan, -1.27109382, -0.531361  ],
       [        nan,         nan,  0.02743874]])

In [70]:
np.log2(arr1)

<ipython-input-70-b8a38c33f7f8>:1: RuntimeWarning: invalid value encountered in log2
  np.log2(arr1)


array([[        nan, -0.75999053, -1.01769105],
       [        nan, -1.31410103, -3.50523782],
       [        nan,         nan,         nan],
       [        nan, -4.22248226, -1.76514303],
       [        nan,         nan,  0.09114953]])

In [71]:
# 각 성분의 부호 계산하기(+인 경우 1, -인 경우 -1, 0인 경우 0)
np.sign(arr1)

array([[-1.,  1.,  1.],
       [-1.,  1.,  1.],
       [-1., -1., -1.],
       [-1.,  1.,  1.],
       [-1., -1.,  1.]])

In [72]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값을 계산하기
np.ceil(arr1)

array([[-1.,  1.,  1.],
       [-0.,  1.,  1.],
       [-0., -0., -1.],
       [-0.,  1.,  1.],
       [-0., -0.,  2.]])

In [73]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기
np.floor(arr1)

array([[-2.,  0.,  0.],
       [-1.,  0.,  0.],
       [-1., -1., -2.],
       [-1.,  0.,  0.],
       [-1., -1.,  1.]])

In [74]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [75]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [76]:
np.isnan(np.log(arr1))

<ipython-input-76-6bad7ca87a38>:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(arr1))


array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True, False]])

In [77]:
# 각 성분이 무한대인 경우 True를, 아닌 경우 False를 반환하기
np.isinf(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [78]:
# 각 성분에 대해 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)
np.cos(arr1)

array([[0.40395097, 0.83066228, 0.88048778],
       [0.77031327, 0.92021143, 0.99612452],
       [0.57300199, 0.9443085 , 0.10081918],
       [0.63991166, 0.99856557, 0.95703515],
       [0.99579768, 0.89567057, 0.48431297]])

In [79]:
np.tanh(arr1)

array([[-0.81939206,  0.53025527,  0.45731122],
       [-0.59892171,  0.38180931,  0.08784105],
       [-0.74455872, -0.32328353, -0.89954036],
       [-0.70461779,  0.05351691,  0.28599361],
       [-0.09145273, -0.43078451,  0.78765301]])

### 6-2. 두 개의 array에 적용되는 함수

In [80]:
arr1

array([[-1.15496454,  0.59050021,  0.49390619],
       [-0.69146405,  0.40217602,  0.08806803],
       [-0.96063218, -0.33530954, -1.46980557],
       [-0.87641303,  0.05356809,  0.29419752],
       [-0.09170898, -0.46085955,  1.06521861]])

In [81]:
arr2 = np.random.randn(5,3)

In [82]:
arr2

array([[-0.08227866,  0.95472531, -1.33291113],
       [-0.1504878 , -0.60151345, -0.42407145],
       [ 0.27476224, -0.12255333,  0.80567595],
       [ 0.49924074, -0.44480715, -1.78544033],
       [-0.25374241,  0.69682322, -2.25554616]])

In [83]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기(add, subtract, multiply, divide)
np.multiply(arr1,arr2)

array([[ 0.09502894,  0.5637655 , -0.65833306],
       [ 0.1040569 , -0.24191429, -0.03734714],
       [-0.26394545,  0.0410933 , -1.18418699],
       [-0.43754109, -0.02382747, -0.52527211],
       [ 0.02327046, -0.32113764, -2.40264974]])

In [84]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 계산하기(maximum, minimum)
np.maximum(arr1,arr2)

array([[-0.08227866,  0.95472531,  0.49390619],
       [-0.1504878 ,  0.40217602,  0.08806803],
       [ 0.27476224, -0.12255333,  0.80567595],
       [ 0.49924074,  0.05356809,  0.29419752],
       [-0.09170898,  0.69682322,  1.06521861]])

### 6-3. 통계 함수
통계 함수를 통해 array의 합이나 평균등을 구할 때,

추가로 axis라는 인자에 대한 값을 지정하여 열 또는 행의 합 또는 평균등을 구할 수 있다.

In [85]:
arr1

array([[-1.15496454,  0.59050021,  0.49390619],
       [-0.69146405,  0.40217602,  0.08806803],
       [-0.96063218, -0.33530954, -1.46980557],
       [-0.87641303,  0.05356809,  0.29419752],
       [-0.09170898, -0.46085955,  1.06521861]])

In [86]:
# 전체 성분의 합을 계산
np.sum(arr1)

-3.0535227770373723

In [87]:
# 열 간의 합을 계산
np.sum(arr1, axis=1)

array([-0.07055814, -0.20122   , -2.76574729, -0.52864742,  0.51265008])

In [88]:
# 행 간의 합을 계산
np.sum(arr1, axis=0)

array([-3.77518278,  0.25007523,  0.47158477])

In [89]:
# 전체 성분의 평균을 계산
np.mean(arr1)

-0.2035681851358248

In [90]:
# 행 간의 평균을 계산
np.mean(arr1, axis=0)

array([-0.75503656,  0.05001505,  0.09431695])

In [91]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)
np.std(arr1)

0.7005326648000988

In [92]:
np.min(arr1, axis=1)

array([-1.15496454, -0.69146405, -1.46980557, -0.87641303, -0.46085955])

In [93]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환(argmin, argmax)
np.argmin(arr1)

8

In [94]:
np.argmax(arr1,axis=0)

array([4, 0, 4], dtype=int64)

In [95]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱을 계산(cumsum, cumprod)
np.cumsum(arr1)

array([-1.15496454, -0.56446433, -0.07055814, -0.76202219, -0.35984617,
       -0.27177814, -1.23241033, -1.56771986, -3.03752543, -3.91393846,
       -3.86037037, -3.56617286, -3.65788183, -4.11874138, -3.05352278])

In [96]:
np.cumsum(arr1,axis=1)

array([[-1.15496454, -0.56446433, -0.07055814],
       [-0.69146405, -0.28928803, -0.20122   ],
       [-0.96063218, -1.29594172, -2.76574729],
       [-0.87641303, -0.82284494, -0.52864742],
       [-0.09170898, -0.55256853,  0.51265008]])

In [97]:
np.cumprod(arr1)

array([-1.15496454e+00, -6.82006798e-01, -3.36847377e-01,  2.32917851e-01,
        9.36739746e-02,  8.24968225e-03, -7.92491027e-03,  2.65729799e-03,
       -3.90571138e-03,  3.42301635e-03,  1.83364457e-04,  5.39453677e-05,
       -4.94727459e-06,  2.27999874e-06,  2.42869708e-06])

### 6-4. 기타 함수

In [98]:
arr1

array([[-1.15496454,  0.59050021,  0.49390619],
       [-0.69146405,  0.40217602,  0.08806803],
       [-0.96063218, -0.33530954, -1.46980557],
       [-0.87641303,  0.05356809,  0.29419752],
       [-0.09170898, -0.46085955,  1.06521861]])

In [99]:
# 전체 성분에 대해서 오름차순으로 정렬
np.sort(arr1)

array([[-1.15496454,  0.49390619,  0.59050021],
       [-0.69146405,  0.08806803,  0.40217602],
       [-1.46980557, -0.96063218, -0.33530954],
       [-0.87641303,  0.05356809,  0.29419752],
       [-0.46085955, -0.09170898,  1.06521861]])

In [100]:
# 전체 성분에 대해서 내림차순으로 정렬
np.sort(arr1)[::-1]

array([[-0.46085955, -0.09170898,  1.06521861],
       [-0.87641303,  0.05356809,  0.29419752],
       [-1.46980557, -0.96063218, -0.33530954],
       [-0.69146405,  0.08806803,  0.40217602],
       [-1.15496454,  0.49390619,  0.59050021]])

In [101]:
# 행 방향으로 오름차순으로 정렬
np.sort(arr1,axis=0)

array([[-1.15496454, -0.46085955, -1.46980557],
       [-0.96063218, -0.33530954,  0.08806803],
       [-0.87641303,  0.05356809,  0.29419752],
       [-0.69146405,  0.40217602,  0.49390619],
       [-0.09170898,  0.59050021,  1.06521861]])